id: A129D2639
title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of Do Khyentsé
  Yeshé Dorjé
type: translation
pechas:
- I597A67E4
- I8E40F2AB
- IC7BA2C92
- IE09AD976
- I99A49987
- I78FFEEEE
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:47:19.735257
  last_modified_at: 2023-01-04 12:47:19.735280
  collections:
  - Katok Rigdzin Chenpo
  - Works of Tibetan Masters
alignment_to_base:
  I597A67E4/6226: '9575'
  I8E40F2AB/CEB4: '9575'
  IC7BA2C92/A327: '9575'
  IE09AD976/B1A8: '9575'
  I99A49987/050C: '9575'
  I78FFEEEE/E8B3: '9575'
